export type ActionType =
    | 'TypeCharacter'
    | 'DeletePreviousCharacter'
    | 'InsertText'
    | 'RemoveText'
    | 'LeftTrimLine'
    | 'MoveLeft'
    | 'MoveRight'
    | 'MoveUp'
    | 'MoveDown'
    | 'Enter'
    | 'MoveCmdLeft'
    | 'MoveCmdRight'
    | 'Tab'
    | 'ShiftTab'
;